feat(docker): refactor dockerfile + bootstrapping
AEGEE/hubot pull request #1
Opened 2020-09-29 12:42 UTC by serge1peshcoff

1) moved all the dependencies to `package.json`
2) removed all the custom workarounds/bootstrapping, now it's just `npm install` (as it's a node app)
3) removed all bootstrapping scripts (makefile/start-dev.sh) as we now can do it with `./helper.sh --something hubot`

caveats: we need to rebuild the container if the deps list was changed, but this shouldn't happen often right?

2020-10-01 07:19 UTC, linuxbandit commented
and it just works?

2020-10-01 07:22 UTC, serge1peshcoff commented
It should in theory. From what I've tested, the container is building, the app is starting with no errors, but I couldn't make it react to my slack messages. This should be something with my setup though

2020-10-01 09:45 UTC, linuxbandit commented
then it doesn't just work :D I don't remember the rationale of doing it this way when it was already working and it was following all the 'standards'/guides (building through yeoman etc)?

2020-10-01 09:51 UTC, serge1peshcoff commented
point is, we can do it once when creating a project, and we can also do it every time we start/build the container, while we won't need it most of the time.
Anyway, I won't merge this until I can make it work locally

2020-10-01 10:13 UTC, serge1peshcoff commented
yep, it works for me now

2020-10-03 10:10 UTC, linuxbandit commented
i will test it too, Idk it doesn't convince me doing different than all the setup guides

2020-10-03 10:12 UTC, linuxbandit requested changes
also imho the name `hubot-slack-docker` is more specific, which is good

2020-10-03 10:12 UTC, linuxbandit commented on docker/Dockerfile
> -FROM node:14.2 AS builder
better use `-alpine`

2020-10-03 10:12 UTC, linuxbandit commented on docker/Dockerfile
> -USER hubot
also run as unprivileged

2020-10-03 10:12 UTC, linuxbandit commented on docker/Dockerfile
> +CMD npx hubot -a slack
use ENTRYPOINT, not CMD

2020-10-11 18:51 UTC, serge1peshcoff commented
@linuxbandit can you check once more?

2020-10-20 09:49 UTC, linuxbandit approved these changes
Still skeptic about the different building system (+ this way if we add a plugin we have to rebuild instead of simply relaunching the container, but that is minor). Buuut if it works for you, be it

2020-10-20 11:21 UTC, merged

2020-10-20 12:51 UTC, serge1peshcoff commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/AEGEE/hubot/releases/tag/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: